server:
  port: 8080
  servlet:
    context-path: /where-is-my-home

spring:
  application:
    name: where-is-my-home

  
#datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssafyhome?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafyssafy

#redis
  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.naver.com
    port: 465
    username: dons97@naver.com
    password: PX7RT6KLL829
    transport:
      protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.naver.com
            enable: true


spring-doc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs

#mybatis
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.home.dto;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

email:
  from: dons97@naver.com